"""
定义的全局变量
"""
PLATFORM = "wechat"
"""平台名称"""
IMPL = "ComWechat"
"""实现端名称"""
VERSION = "v1.0"
"""版本"""
ONEBOT = "OneBot"
"""onebot名称"""
ONEBOT_VERSION = "12"
"""onebot版本"""
USER_AGENT = "OneBot/12(ComWeChat)"
"""协议头ua"""
PREFIX = "wx"
"""拓展前缀"""

FILE_CACHE = "file_cache"
"""保存文件缓存目录，为了防止意外，不要和其他目录放在一起"""
LOG_PATH = "log"
"""日志存放目录"""
DATABASE_PATH = "data"
"""数据库存放目录"""
DOWNLOAD_TIMEOUT = 10
"""下载超时时间"""
